### PR TITLE
Don't look for `body` in an ApiError

### PR DESCRIPTION
**Pull request by AndrewFerr**
Instead, look for `jsonBody`

### CODE REVIEW

**Comment by AndrewFerr** [comment]
This could have been more easily noticed if [type-checking on errors wasn't disabled](https://github.com/matrix-org/matrix-hookshot/blob/563603ff76be724fb7f2531a291813ea56ade169/tsconfig.json#L26-L27) (thanks @justinbot for pointing out that config!).

It's still too early to turn it on, though, as Hookshot still uses a version of `matrix-bot-sdk` that doesn't expose its ubiquitous `MatrixError` type, which would be one of the primary errors to type-check.

**Comment by AndrewFerr** [comment]
Oh, and this should fix https://github.com/matrix-org/matrix-hookshot/issues/456

**Comment by AndrewFerr** [comment]
Just confirmed that this indeed fixes #456:
image

Note that I'm the only person in the room (see "People 1" on the right sidebar) and no error markers appear. The "Bridges" items are clickable & work properly.

**Review by Half-Shot — APPROVED** [review]
Looks good. I've patched upstream so we can access the error object https://github.com/turt2live/matrix-bot-sdk/pull/257.

Technically you can still access the error object by importing the MatrixError.ts file directly in the code, but I wouldn't begrudge you for wanting to do something less hacky!

**Pull request merged**
