### PR TITLE
Maintainer Gitlab perms instead of Developer.

### LINKED ISSUE #545: Improve hookshook error message when gitlab token doesn't have the "maintainer" role e.g "Failed to create connection because of insufficient permissions"
* The gitlab token needs the gitlab `maintainer` role ; the gitlab `developer` role is not sufficient.
image

### PR DESCRIPTION
**Pull request by rtanglao**
* Gnome needed to use Gitlab `maintainer` permissions, partially fixes #545

### CODE REVIEW

**Review by AndrewFerr — CHANGES_REQUESTED** [review]
There is no "Moderator" role, but there is a "Maintainer" one.

I also want to confirm that it's indeed forbidden for "Developer"s to simply _list_ available webhooks, which should be sufficient for preparing a Hookshot connection for a repo's existing webhooks.

If there isn't, we'll also have to update the bot's error message of "You must at least have developer access to bridge this project".

**Comment by rtanglao** [comment]
> There is no "Moderator" role, but there is a "Maintainer" one.
Oops fixed it!

> I also want to confirm that it's indeed forbidden for "Developer"s to simply _list_ available webhooks, which should be sufficient for preparing a Hookshot connection for a repo's existing webhooks.
> 
didn't touch this, how do I confirm this?

> If there isn't, we'll also have to update the bot's error message of "You must at least have developer access to bridge this project
i'll leave this to you @AndrewFerr :-)

**Comment by rtanglao** [comment]
closed by accident, please re-review :-)

**Comment by AndrewFerr** [comment]
As it turns out, the Maintainer role is only needed for Hookshot to add a webhook to the project.  Given that disabling automatic webhook creation in the config is possible & would bypass this error, we should allow this missing permission & just behave as though webhook creation was disabled.

That and more is handled in https://github.com/matrix-org/matrix-hookshot/pull/567.

**Pull request closed without merging**
