### PR TITLE
sucessfully

### PR DESCRIPTION
**Pull request by tsimonq2**
https://github.com/calamares/calamares/issues/2263

### CODE REVIEW

**Review by Half-Shot — APPROVED** [review]
Thanks, I should really run a spell checker on some of these strings :)

**Comment by Half-Shot** [comment]
@tsimonq2 would you mind doing a signoff?

**Comment by tsimonq2** [comment]
@Half-Shot Not a problem! Are you looking for a signed-off-by line or a signed commit?

Simon Quigley <tsimonq2@ubuntu.com> works for the former (or pick any other email address from my Launchpad profile)

**Comment by tsimonq2** [comment]
In case I lose track of this today, I, Simon Quigley explicitly agree to contribute my code under the existing Matrix license: https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off

**Comment by Half-Shot** [comment]
Perfectly valid thanks!

**Pull request merged**
